export const standardPackageOptions = [
  "Full solution",
  "All solution attachments",
];

export const issueTypes = [
  { label: "Additional electric parts", value: "Additional electric parts" },
  { label: "Body and exterior", value: "Body and exterior" },
  { label: "Control and suspension", value: "Control and suspension" },
  {
    label: "Driving support and security",
    value: "Driving support and security",
  },
  { label: "Energy system", value: "Energy system" },
  { label: "Engine", value: "Engine" },
  { label: "Interior", value: "Interior" },
  { label: "Sensors", value: "Sensors" },
];

export const issueTypeOptions = {
  "Additional electric parts": [
    "Various motors",
    "Electric cable",
    "Actuator",
    "Semiconductor",
    "Wire harness",
    "Relay",
    "Hidden switch",
    "Electric connector",
  ],
  "Body and exterior": [
    "Body Reinforcement/protector",
    "Door",
    "Wiper",
    "Outside mirror",
    "Body panel",
    "Weather strip",
    "Frame",
    "Bumper",
    "lamp",
    "Fuel tank",
    "Key set",
    "Rear end module",
    "Pedal",
    "Horn",
    "Gas spring",
  ],
  "Control and suspension": [
    "Axle",
    "Sub brake",
    "Brake by wire",
    "Air brake",
    "Vehicle Dynamic Control system",
    "Weather strip",
    "Frame",
    "Bumper",
    "Lamp",
    "Fuel tank",
    "Key set",
    "Pedal",
  ],
  "Driving support and security": [
    "Telematics, car navigation",
    "Entertainment, audio",
    "Security system",
    "Monitoring system",
    "Cruise control system",
  ],
  "Energy system": [
    "Heather",
    "Air Conditioner",
    "Fuel cell system",
    "Battery/Capacitor",
    "Power control system",
    "Drive train system",
  ],
  Engine: [
    "Air/Fuel management",
    "Fuel handling and Evapo system",
    "Turbo/Supercharger",
    "Exhaust system",
    "Engine control system",
    "Ignition system",
    "Engine electric system",
    "Diesel injection system",
    "Valvetrain",
    "Engine cooling system",
    "Gasoline fuel injection system",
    "Engine lubricating system",
  ],
  Interior: [
    "Cockpit module",
    "Instrument switch",
    "Instrument switch",
    "Airbag system",
    "Interior trim",
    "Instrumental panel",
  ],
  Sensors: [
    "Airbag",
    "ABS",
    "Oil",
    "Fuel",
    "Air",
    "Speed",
    "Gas",
    "Solar",
    "G",
    "Vacuum",
  ],
};

export const transmissionOptions = ["Manual", "Semi-automatic", "Automatic"];

export const fuelTypeOptions = [
  "Petrol",
  "Diesel",
  "Electric",
  "Ethanol (FFV, E85, etc.)",
  "Hybrid (Petrol/Electric)",
  "Hybrid (Diesel/Electric)",
  "Hydrogen",
  "Natural gas",
  "Other",
];

export const advertiseOptions = {
  position: [
    { value: 0, label: "No top position advertisements" },
    { value: 5, label: "3 days for 5 tokens" },
    { value: 10, label: "7 days for 10 tokens" },
    { value: 15, label: "14 days for 15 tokens" },
  ],
  notifications: [
    { value: 0, label: "No notification advertisements" },
    { value: 5, label: "3 days for 5 tokens" },
    { value: 10, label: "7 days for 10 tokens" },
    { value: 15, label: "14 days for 15 tokens" },
  ],
};
